name: Publish NuGet Package to GitHub Packages

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Build and Publish to GitHub Packages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0'

      - name: Print working directory
        run: pwd

      - name: List files
        run: ls -R

      - name: Restore dependencies
        run: dotnet restore ./src/LibraryEngine/library.core.domain/library.core.domain.csproj

      - name: Build
        run: dotnet build ./src/LibraryEngine/library.core.domain/library.core.domain.csproj --configuration Release --no-restore

      - name: Pack
        run: dotnet pack ./src/LibraryEngine/library.core.domain/library.core.domain.csproj --configuration Release --no-build --output ./nupkg

      - name: Push to GitHub Packages
        run: dotnet nuget push ./nupkg/*.nupkg --source "github" --api-key ${{ secrets.NUGETS_GIO_KEY }}